name: CI
on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

env:
  CI: true

jobs:
  tests:
    name: ESLint, Prettier, Grammar Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install
      run: npm ci
    - name: ESLint
      run: npm run ci:eslint
    - name: Prettier
      if: '!cancelled()'
      run: npm run ci:prettier
    - name: Grammar
      if: '!cancelled()'
      run: npm run grammar:test
  typescript:
    name: TypeScript Compiler Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install
      run: npm ci
    - name: TypeScript
      run: npm run ci:tsc