on:
  push:
    tags: ["v*"]
  workflow_dispatch:

env:
  CI: true
  PRE_RELEASE: ${{ endsWith(github.ref_name, '-pre') }}

name: Release & Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease: ${{ env.PRE_RELEASE }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
      - name: Upload vsix
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}